sourceofstuff/sourceofstuff/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

from items.views import ItemDetailView, ItemCreateView, \
    ItemListView, ItemEditView, ItemVoteView

urlpatterns = patterns('',
    url(r'^$', ItemListView.as_view(), name="home"),

    url(r'^join$', 'contributors.views.join_view'),
    url(r'^authenticate$', 'contributors.views.authenticate_view'),
    url(r'^logout$', 'contributors.views.logout_view'),
    url('', include('social.apps.django_app.urls', namespace='social')),

    url(r'^item/(?P<pk>\d+)/$', ItemDetailView.as_view(), name="item-detail"),
    url(r'^item/list/(?P<page>\d+)/$', ItemListView.as_view(), name="item-list"),
    url(r'^item/create/$', ItemCreateView.as_view(), name="item-create"),
    url(r'^item/edit/(?P<pk>\d+)/$', ItemEditView.as_view(), name="item-edit"),
    url(r'^item/vote/(?P<vote>[a-z]+)/(?P<pk>\d+)/$', ItemVoteView.as_view(), name="item-vote"),

    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sourceofstuff/items/models.py
from django.db import models
from contributors.models import Contributor
from taggit.managers import TaggableManager


class Reference(models.Model):
    src = models.URLField()
    views = models.IntegerField(default=0)
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.src

    class Meta:
        ordering = ('-time_created',)


class Item(models.Model):
    name = models.CharField(max_length=50)
    cover = models.ImageField(upload_to='items/', blank=True, null=True)
    summary = models.CharField(max_length=250)

    first_mentioned = models.CharField(max_length=20, blank=True, null=True)
    geographic_origin = models.CharField(blank=True, null=True, max_length=100)
    inventor = models.CharField(blank=True, null=True, max_length=100)

    origin_story = models.TextField()

    contributors = models.ManyToManyField(Contributor,
                                          related_name="item_contributors")
    raters = models.ManyToManyField(Contributor,
                                    related_name="item_raters",
                                    blank=True, null=True)

    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)

    tags = TaggableManager()

    time_created = models.DateTimeField(auto_now_add=True)
    last_accessed = models.DateTimeField(blank=True, null=True)
    last_modified = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-time_created',)

sourceofstuff/items/forms.py
from django.forms import ModelForm
from .models import Item


class ItemForm(ModelForm):
    class Meta:
        model = Item
        exclude = ['contributors', 'upvotes', 'downvotes', 'last_accessed', 'last_modified']

    def __init__(self, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['cover'].widget.attrs['class'] = 'form-control'
        self.fields['summary'].widget.attrs['class'] = 'form-control'
        self.fields['origin_story'].widget.attrs['class'] = 'form-control'
        self.fields['first_mentioned'].widget.attrs['class'] = 'form-control'
        self.fields['geographic_origin'].widget.attrs['class'] = 'form-control'
        self.fields['inventor'].widget.attrs['class'] = 'form-control'
        self.fields['tags'].widget.attrs['class'] = 'form-control'

sourceofstuff/items/views.py
from django.views.generic import DetailView, View
from django.utils import timezone
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django_wysiwyg.utils import clean_html, sanitize_html

from contributors.models import Contributor

from sourceofstuff.keys import SOCIAL_AUTH_TWITTER_KEY, SOCIAL_AUTH_TWITTER_SECRET

from twython import Twython

from .models import Item
from .forms import ItemForm


class ItemListView(View):
    template_name = 'item_list.html'

    def get(self, request, page=None, modifier=None, *args, **kwargs):
        callback = {}
        if modifier:
            print "using a modifier"
            item_list = Item.objects.all()
        else:
            item_list = Item.objects.all()
        # Pagination: https://docs.djangoproject.com/en/1.7/topics/pagination/
        paginated_items = Paginator(item_list, 9)
        try:
            items = paginated_items.page(page)
            callback['next_page'] = int(page) + 1
        except PageNotAnInteger:
            items = paginated_items.page(1)
            callback['next_page'] = 2
        except EmptyPage:
            items = paginated_items.page(paginated_items.num_pages)
        except Exception as e:
            print e
            items = None

        callback['item_list'] = items
        if page is None:
            callback['first_page'] = True
        #################################################################
        # This is a hack - because twitter profile pic is annoying to get
        if request.user.id is not None:
            if request.user.profile_img_url is None:
                user = Contributor.objects.get(username=request.user)
                social = user.social_auth.get(provider='twitter')
                access_token = social.extra_data['access_token']

                t = Twython(app_key=SOCIAL_AUTH_TWITTER_KEY,
                            app_secret=SOCIAL_AUTH_TWITTER_SECRET,
                            oauth_token=access_token[u'oauth_token'],
                            oauth_token_secret=access_token[u'oauth_token_secret'])

                twitter_account = t.show_user(screen_name=request.user.username)
                profile_img_url = twitter_account[u'profile_image_url']
                user.profile_img_url = profile_img_url
                user.save()
        #################################################################

        return render(request, self.template_name, callback)


class ItemDetailView(DetailView):
    template_name = 'item.html'
    queryset = Item.objects.all()

    def get_object(self):
        # Call the superclass
        object = super(ItemDetailView, self).get_object()
        # Record the last accessed date
        object.last_accessed = timezone.now()
        object.save()
        # Clean the html
        object.origin_story = clean_html(object.origin_story)
        # Return the object
        return object

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ItemDetailView, self).get_context_data(**kwargs)
        return context


class ItemCreateView(View):
    template_name = 'item_create.html'

    def get(self, request, *args, **kwargs):
        callback = {}
        itemForm = ItemForm()
        callback['itemForm'] = itemForm
        return render(request, self.template_name, callback)

    def post(self, request, *args, **kwargs):
        callback = {}
        itemForm = ItemForm(request.POST, request.FILES)

        if itemForm.is_valid():
            item = itemForm.save(commit=False)
            item.origin_story = sanitize_html(item.origin_story)
            item.origin_story = clean_html(item.origin_story)
            item.save()
            item.contributors.add(request.user)

            # Handle the tagging
            for tag in itemForm.cleaned_data['tags']:
                item.tags.add(tag)

            return redirect('/item/'+str(item.id))
        callback['itemForm'] = itemForm  # return form with errors
        return render(request, self.template_name, callback)


class ItemEditView(View):
    template_name = 'item_edit.html'

    def get(self, request, pk, *args, **kwargs):
        callback = {}
        item = Item.objects.get(pk=pk)
        callback['item'] = item
        itemForm = ItemForm(instance=item)
        callback['itemForm'] = itemForm
        return render(request, self.template_name, callback)

    def post(self, request, pk, *args, **kwargs):
        callback = {}
        item = Item.objects.get(pk=pk)
        itemForm = ItemForm(request.POST, instance=item)
        if itemForm.is_valid():
            item = itemForm.save(commit=False)
            item.last_modified = timezone.now()
            item.save()

            # Tags
            for tag in item.tags.all():
                item.tags.remove(tag)
            for tag in itemForm.cleaned_data['tags']:
                item.tags.add(tag)

            # if this is a new contributor add them
            if Item.objects.filter(contributors__pk=request.user.pk).count() == 0:
                item.contributors.add(request.user)
            return redirect('/item/'+str(item.id))
        callback['itemForm'] = itemForm  # return form with errors
        return render(request, self.template_name, callback)


class ItemVoteView(View):
    def get(self, request, vote, pk, *args, **kwargs):
        item = Item.objects.get(pk=pk)

        if request.user in item.raters.all():
            print "User rated this, skip"
        else:
            print "User did not rate this, go on"

            if vote == 'up':
                item.upvotes += 1
                item.save()
            elif vote == 'down':
                item.downvotes += 1
                item.save()
            else:
                return redirect('/item/'+str(item.id))

            item.raters.add(request.user)

        return redirect('/item/'+str(item.id))

sourceofstuff/templates/base.html
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/bootstrap-paper.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'bower_components/ionicons/css/ionicons.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/app.css' %}" type="text/css" />
    {% block extra_styles %} {% endblock %}
  </head>
  <body>
    <!-- Navbar -->
    <div class="navbar navbar-inverse" style="border-radius:0px;">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Source of Stuff</a>
      </div>
      <div class="navbar-collapse collapse navbar-inverse-collapse">
        <!-- <form class="navbar-form navbar-left">
          <input type="text" class="form-control col-lg-8" placeholder="Search">
        </form> -->
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <!-- <li><a href="#" class="ion-ios-keypad-outline"style="font-size:25px;"></a></li> -->
            <li><a href="/item/create/" class="ion-ios-plus-outline"style="font-size:25px;"></a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{user.username}} <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <!-- <li><a href="#">Profile</a></li>
                <li><a href="#">Settings</a></li>
                <li class="divider"></li> -->
                <li><a href="#" data-toggle="modal" data-target="#contributeModal">Contribute</a></li>
                <li class="divider"></li>
                <li><a href="/logout">Logout</a></li>
              </ul>
            </li>
          {% else %}
            <li><a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}">Login with Twitter</a></li>
          {% endif %}
          
        </ul>
      </div>
    </div>
    <!-- /END Navbar -->

    <!-- Contribute Modal -->
    <div class="modal fade" id="contributeModal" tabindex="-1" role="dialog" aria-labelledby="contributeModal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Contribute to Source of Stuff</h4>
          </div>
          <div class="modal-body">
            <p>Source of Stuff is an effort to catalog and archive the not so ordinary origins of ordinary items found around the world!</p>
            <p>If you are finding Source of Stuff an educational and useful tool, consider contributing to the project effort</p>

            <hr>
            
            <div class="text-center">
              <a target="_blank" href="https://twitter.com/SourceOfStuff" class="btn btn-primary">Twitter</a>
            </div>

            <hr>
            <div class="text-center">
              <a target="_blank" href="https://github.com/AVatch/SourceOfStuff" class="btn btn-default">GitHub Repo</a>              
            </div>

            <hr>

            <p>Thank you, and look forward to new updates and features :)</p>

          </div>
        </div>
      </div>
    </div>
    <!-- /Contribute Modal -->

    {% block content %} {% endblock %}

    <script src="{% static 'bower_components/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.js' %}"></script>

    <script type="text/javascript">
      $('#contributeModal').on('shown.bs.modal', function () {
        $('#contributeModalToggle').focus();
      });
    </script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-54082621-2', 'auto');
      ga('send', 'pageview');

    </script>

    {% block extra_scripts %} {% endblock %}
  </body>
</html>

sourceofstuff/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
{% block item %}{% endblock %}
</div>
{% endblock %}

sourceofstuff/templates/item.html
{% extends 'home.html' %}
{% block item %}
  <div class="container">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row" style="border-bottom:1px solid #eeeeee;">
            <div class="col-xs-8">
                <h2>{{item.name}}</h2>
                <p class="lead">{{item.summary}}</p>
            </div>
            <div class="col-xs-4">
                <div class="btn-group btn-group-sm pull-right" role="group">
                    <a href="/item/vote/up/{{item.pk}}" style="outline:none;" type="button" 
                    class="btn btn-default btn-lg {% if not user.is_authenticated %} disabled {% endif %}" data-toggle="tooltip" data-placement="bottom" title="Upvote"><i class="ion-ios-arrow-up"></i> {{item.upvotes}}</a>
                    <a href="/item/vote/down/{{item.pk}}" style="outline:none;" type="button" class="btn btn-default btn-lg {% if not user.is_authenticated %} disabled {% endif %}" data-toggle="tooltip" data-placement="bottom" title="Downvote"><i class="ion-ios-arrow-down"></i> {{item.downvotes}}</a>
                    <a href="/item/edit/{{item.pk}}/" style="outline:none;" type="button" class="btn btn-default btn-lg {% if not user.is_authenticated %} disabled {% endif %}" data-toggle="tooltip" data-placement="bottom" title="Edit">&nbsp<i class="ion-ios-compose-outline"></i>&nbsp</a>
                    <a style="outline:none;" type="button" class="btn btn-default btn-lg {% if not user.is_authenticated %} disabled {% endif %}" data-toggle="tooltip" data-placement="bottom" title="More">&nbsp<i class="ion-ios-more-outline"></i>&nbsp</a>
                </div>
            </div>
        </div><!-- /row 01 -->
        <div class="row" style="padding-top:15px;">
            <div class="col-md-4">
                <div class="row">
                    <div class="col-md-12">
                        {% if item.cover %}
                            <img class="img-rounded" src="{{item.cover.url}}" style="width:350; height=350px;">
                        {% else %}
                            <img class="img-rounded" src="http://placehold.it/350x350" style="width:350; height=350px;">
                        {% endif %}
                    </div>
                    <div class="col-md-12">
                        <h5>First Mention:</h5>
                        {% if item.first_mentioned %}
                            <small>{{item.first_mentioned}}</small>
                        {% else %}
                            {% if user.is_authenticated %}
                                <a href="/item/edit/{{item.pk}}"><small>Contribute to Entry</small></a>
                            {% else %}
                                Please sign in
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class="col-md-12">
                        <h5>Geographic Origin:</h5>
                        {% if item.geographic_origin %}
                            <small>{{item.geographic_origin}}</small>
                        {% else %}
                            {% if user.is_authenticated %}
                                <a href="/item/edit/{{item.pk}}"><small>Contribute to Entry</small></a>
                            {% else %}
                                Please sign in
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class="col-md-12">
                        <h5>Inventor:</h5>
                        {% if item.inventor %}
                            <small>{{item.inventor}}</small>
                        {% else %}
                            {% if user.is_authenticated %}
                                <a href="/item/edit/{{item.pk}}"><small>Contribute to Entry</small></a>
                            {% else %}
                                Please sign in
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class="col-md-12">
                        <h5>Contributors:</h5>
                        {% for contributor in item.contributors.all %}
                            {% if contributor.profile_img_url %}
                                <a target="_blank" href="https://twitter.com/{{contributor.username}}">
                                    <img class="img-circle" src="{{contributor.profile_img_url}}" style="width:48px; height:48px;">
                                </a>
                            {% else %}
                                <img class="img-circle" src="http://placehold.it/50x50" style="width:48px; height:48px;">
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="col-md-12">
                        <h5>Tags:</h5>
                        {% for tag in item.tags.all %}
                            {{tag}},
                        {% endfor %}
                        {% if user.is_authenticated %}
                            <a href="/item/edit/{{item.pk}}"><small>Add tags</small></a>
                        {% endif %}
                    </div>
                    <!-- <div class="col-md-12">
                        <h5>References:</h5>
                        <p>Link01</p>
                        <p>Link01</p>
                        <p>Link01</p>
                        <p>Link01</p>
                    </div> -->
                </div>    
            </div>
            <div class="col-md-8">
                <div class="origin-container" style="font-size:18px; height:100%; padding:5px; border-radius:5px; background-color:#f5f5f5;">
                    {% autoescape off %}{{item.origin_story}}{% endautoescape %}
                </div>
            </div>
        </div>
      </div>
    </div>

    <!-- <h1>{{item.name}}</h1>
    <hr>
    {% for contributor in item.contributors.all %}
    <span>{{contributor.username}}</span>
    {% endfor %}
    <hr>
    {{item.origin_story}}
    <hr>
    {{item.upvotes}} {{item.downvotes}} -->
  </div>
{% endblock %}

{% block extra_scripts %}
<script type="text/javascript">
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    });
</script>
{% endblock %}

sourceofstuff/templates/item_create.html
{% extends 'home.html' %}

{% load staticfiles %}
{% load wysiwyg %}

{% block item %}
<h3>Add an Item</h3>
<hr>
<form enctype="multipart/form-data" action="/item/create/" method="post" class="form-horizontal">
  {% csrf_token %}

  <div class="form-group">
    <div class="col-md-4">
      <label for="item">Cover Image:</label>
      {{itemForm.cover}}
    </div>
    <div class="col-md-8 {% if itemForm.name.errors %} has-error {% endif %} ">
      <label for="item">Item:</label>
      {{itemForm.name}}
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-3 {% if itemForm.first_mentioned.errors %} has-error {% endif %}">
      <label for="item">First Mentioned:</label>
      {{itemForm.first_mentioned}}
    </div>
    <div class="col-md-3 {% if itemForm.geographic_origin.errors %} has-error {% endif %}">
      <label for="item">Geographic Origin:</label>
      {{itemForm.geographic_origin}}
    </div>
    <div class="col-md-3 {% if itemForm.inventor.errors %} has-error {% endif %}">
      <label for="item">Inventor:</label>
      {{itemForm.inventor}}
    </div>
    <div class="col-md-3 {% if itemForm.tags.errors %} has-error {% endif %}">
      <label for="item">Tags (Comma Seperate):</label>
      {{itemForm.tags}}
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-12 {% if itemForm.summary.errors %} has-error {% endif %}">
      <label for="item">Summary (<span id="chars"></span> chars):</label>
      {{itemForm.summary}}
    </div>
  </div>

  <div class="form-group {% if itemForm.origin_story.errors %} has-error {% endif %}">
    <div class="col-md-12">
      <label for="item">Origin Story:</label>
      {{itemForm.origin_story.errors}}
      {{itemForm.origin_story}}
      {% wysiwyg_editor "id_origin_story" %}
    </div>
  </div>

  <button type="submit" class="btn btn-primary pull-right">Create</button>
</form>

<span style="display:block; height:50px;"></span>

{% endblock %}

{% block extra_styles %} 
<link rel="stylesheet" href="{% static 'bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css' %}" type="text/css" />
{% wysiwyg_setup  %}

<style type="text/css">
  .yui-editor-container{
    width:100% !important;
  }
</style>
{% endblock %}

{% block extra_scripts %}
<script type="text/javascript">
  var summaryCharLimit = 250;
  $('#chars').html(summaryCharLimit.toString());

  $('#id_summary').keypress(function(){    
    $('#chars').html((summaryCharLimit - $('#id_summary').val().length).toString());
  });
</script>
{% endblock %}

sourceofstuff/templates/item_edit.html
{% extends 'home.html' %}

{% load staticfiles %}
{% load wysiwyg %}

{% block item %}
<h3>Edit an Item</h3>
<hr>

<form action="/item/edit/{{item.pk}}/" method="post" class="form-horizontal">
  {% csrf_token %}
  
  <div class="form-group">
    <div class="col-md-4">
      <label for="item">Cover Image:</label>
      {{itemForm.cover}}
    </div>
    <div class="col-md-8 {% if itemForm.name.errors %} has-error {% endif %} ">
      <label for="item">Item:</label>
      {{itemForm.name}}
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-3 {% if itemForm.first_mentioned.errors %} has-error {% endif %}">
      <label for="item">First Mentioned:</label>
      {{itemForm.first_mentioned}}
    </div>
    <div class="col-md-3 {% if itemForm.geographic_origin.errors %} has-error {% endif %}">
      <label for="item">Geographic Origin:</label>
      {{itemForm.geographic_origin}}
    </div>
    <div class="col-md-3 {% if itemForm.inventor.errors %} has-error {% endif %}">
      <label for="item">Inventor:</label>
      {{itemForm.inventor}}
    </div>
    <div class="col-md-3 {% if itemForm.tags.errors %} has-error {% endif %}">
      <label for="item">Tags (Comma Seperate):</label>
      {{itemForm.tags}}
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-12 {% if itemForm.summary.errors %} has-error {% endif %}">
      <label for="item">Summary (<span id="chars"></span> chars):</label>
      {{itemForm.summary}}
    </div>
  </div>

  <div class="form-group {% if itemForm.origin_story.errors %} has-error {% endif %}">
    <div class="col-md-12">
      <label for="item">Origin Story:</label>
      {{itemForm.origin_story.errors}}
      {{itemForm.origin_story}}
      {% wysiwyg_editor "id_origin_story" %}
    </div>
  </div>

  <button type="submit" class="btn btn-primary pull-right">Edit</button>
</form>

<span style="display:block; height:50px;"></span>

{% endblock %}

{% block extra_styles %} 
<link rel="stylesheet" href="{% static 'bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css' %}" type="text/css" />
{% wysiwyg_setup  %}

<style type="text/css">
  .yui-editor-container{
    width:100% !important;
  }
</style>
{% endblock %}

{% block extra_scripts %}
<script type="text/javascript">
  var summaryCharLimit = 250;
  $('#chars').html(summaryCharLimit.toString());

  $('#id_summary').keypress(function(){    
    $('#chars').html((summaryCharLimit - $('#id_summary').val().length).toString());
  });
</script>
{% endblock %}

sourceofstuff/templates/item_list.html
{% extends 'home.html' %}

{% block item %}
  <div class="row">

    <!-- Warning Msg -->
    {% if first_page %}
    <div class="alert alert-dismissable alert-warning">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4>Beta Product!</h4>
      <p>Source of Stuff is still in development so be kind and understanding. If you encounter any errors feel free to drop an issue report at the <a target="_blank" href="https://github.com/AVatch/SourceOfStuff" class="alert-link">Github Repo</a>.</p>
    </div>
    {% endif %}
    <!-- /Warning Msg -->

  {% for item in item_list %}
  
    <div class="col-md-4">
      <div class="panel panel-default" style="height:400px;">
        <div class="panel-heading">    
          <h3 class="panel-title"><a href="/item/{{item.pk}}">{{item.name}}</a></h3>

        </div>
        <div class="panel-body">
          <div class="cover-container" style="display:block; height:50%; overflow:hidden;">
            {% if item.cover %}
              <a href="/item/{{item.pk}}">
                <img class="img-rounded" src="{{item.cover.url}}" style="width:100%; height=100%;">
              </a>
            {% else %}
              <a href="/item/{{item.pk}}">
                <img class="img-rounded" src="http://placehold.it/350x350" style="width:100%; height=100%;">
              </a>
            {% endif %}
          </div>
          <div class="contributor-container" style="padding:5px; overflow:auto; white-space:nowrap;">
            {% for contributor in item.contributors.all %}
              {% if contributor.profile_img_url %}
                <a target="_blank" href="https://twitter.com/{{contributor.username}}">
                  <img class="img-circle" src="{{contributor.profile_img_url}}" style="width:48px; height:48px;">
                </a>
              {% else %}
                <img class="img-circle" src="http://placehold.it/50x50" style="width:48px; height:48px;">
              {% endif %}
            {% endfor %}
          </div>
          <div class="summary-container" style="display:block; height:20%; overflow-y:auto; padding:5px; border-radius:5px; background-color:#f5f5f5;">
            {{item.summary}}
          </div>
        </div>
      </div>
    </div>
  
  {% endfor %}
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      {% if next_page %}
        <a href="/item/list/{{next_page}}" class="btn btn-primary">Load More</a>
      {% endif %}
    </div>
  </div>
  <span style="display:block; height:50px;"></span>
{% endblock %}